"""Removed  username to Task model

Revision ID: 39abf0f2eb7a
Revises: 951b002537ab
Create Date: 2024-05-10 07:32:02.632301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39abf0f2eb7a'
down_revision: Union[str, None] = '951b002537ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_username_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('tasks_username_fkey', 'tasks', 'users', ['username'], ['username'])
    # ### end Alembic commands ###
