"""Added username to Task model

Revision ID: 951b002537ab
Revises: 3e213b309260
Create Date: 2024-05-10 07:29:01.144899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951b002537ab'
down_revision: Union[str, None] = '3e213b309260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('username', sa.String(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'username')
    # ### end Alembic commands ###
